### ISSUE TITLE
Four arrows control

### ISSUE THREAD

**Issue by M5oul** [baurst/rs_snake#1]
Hi, thanks for this nice game!

Would that be possible to have a four arrows control feature?

That could be a feature enabled with an option if not set by default.

I would set option this by default.

**Comment by baurst** [comment]
Hi,
thank you for your interest in this project. I have just pushed a new feature to master which enables steering using all four arrow keys/WASD by default. In case the user wants to use the two keys for steering there is the flag --two_key_steering. Have fun playing!
