### ISSUE TITLE
Blind colour

### ISSUE THREAD

**Issue by M5oul** [baurst/rs_snake#2]
I am not sure the choose colours are nice for blind colour people.

I am lightly blind colour, and I have issues to see the red on the black screen on the `Game over` layer.

The colours of the snake could also be better.

I do not know more about how to solve this colours blindness.

**Comment by baurst** [comment]
Hi,
thank you for taking interest in this project. In terms of color support across multiple platforms, we are relying on the crossterm crate, so we are somewhat limited in the choice of colors we can use: https://docs.rs/crossterm/0.14.2/crossterm/style/enum.Color.html
I understand that the lack of contrast is a problem, but I do not have time to work on this right now. I'd be more than happy to accept PRs or suggestions for a new color map, if you feel like it. Thanks!

**Comment by baurst** [comment]
I have updated the color scheme to one with higher contrast. :+1:
